[package]
name = "lightscrape-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html2md = "0.2.14"
rayon = "1.10.0"
regex = "1.10.4"
reqwest = { version = "0.11", features = ["blocking"] }
